use_frameworks!

target 'Adapty_Example' do
  pod 'Adapty', :path => '../'
  
  pod 'Adjust', '~> 4.21.1'
  pod 'AppsFlyerFramework'
  pod 'Branch'

  target 'Adapty_Tests' do
    inherit! :search_paths

    
  end
end
