use_frameworks!
inhibit_all_warnings!

target 'Adapty_Example' do
  project 'Adapty.xcodeproj'
  pod 'Adapty', :path => '../../'
  
  pod 'Adjust', '~> 4.29.6'
  pod 'AppsFlyerFramework', '~> 6.6.0'
  pod 'Branch', '~> 0.33.1'

  target 'Adapty_Tests' do
    inherit! :search_paths

    pod 'Nimble'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
#          if target.name == 'Adapty'
#            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-DADAPTY_DISABLE_PUSHES']
#          end
        end
    end
end
